export const SET_SEARCHED_COSMETICS = 'SET_SEARCHED_COSMETICS'
export const ADD = 'ADD'

//Navigation
export const SET_TAB = 'SET_TAB' 
export const CHANGE_SCENE_COSMETICS_SEARCH = 'CHANGE_SCENE_COSMETICS_SEARCH'