export const SET_SEARCHED_COSMETICS = 'SET_SEARCHED_COSMETICS'
export const SET_COSMETICS_AUTOCOMPLETE_INPUT = 'SET_COSMETICS_AUTOCOMPLETE_INPUT'
export const ADD = 'ADD'

//Navigation
export const SET_TAB = 'SET_TAB' 

//Authen
export const SET_STATUS_USER = 'SET_STATUS_USER' 
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE' 
export const SET_LOGIN_DETAILS= 'SET_LOGIN_DETAILS'

//User detail
export const SET_USER_DETAILS = 'SET_USER_DETAILS' 

//Barcode
export const SET_BARCODE_NUMBER = 'SET_BARCODE_NUMBER' 
export const SET_DEFAULT_ITEM_BARCODE = 'SET_DEFAULT_ITEM_BARCODE'

//Detail Pages
export const SET_DETAILS_COSMETIC = 'SET_DETAILS_COSMETIC' 

//Comments
export const SET_COMMENTS = 'SET_COMMENTS' 

//logs
export const SET_ITEM_LOGS = 'SET_ITEM_LOGS'
